//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab1.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lab1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на スキャナー.
        /// </summary>
        internal static string Ckaner {
            get {
                return ResourceManager.GetString("Ckaner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на コピー.
        /// </summary>
        internal static string CNTRLC {
            get {
                return ResourceManager.GetString("CNTRLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ありがとう.
        /// </summary>
        internal static string CNTRLV {
            get {
                return ResourceManager.GetString("CNTRLV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на こんに.
        /// </summary>
        internal static string ColumnHeader1_Japanese {
            get {
                return ResourceManager.GetString("ColumnHeader1_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 作成する.
        /// </summary>
        internal static string Cozdat {
            get {
                return ResourceManager.GetString("Cozdat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 参考文献.
        /// </summary>
        internal static string CpicokLIter {
            get {
                return ResourceManager.GetString("CpicokLIter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 参照.
        /// </summary>
        internal static string Cpravka {
            get {
                return ResourceManager.GetString("Cpravka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 消去.
        /// </summary>
        internal static string Delet {
            get {
                return ResourceManager.GetString("Delet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 診断とエラーの無力化.
        /// </summary>
        internal static string Diagnostika {
            get {
                return ResourceManager.GetString("Diagnostika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 出口.
        /// </summary>
        internal static string EXIT {
            get {
                return ResourceManager.GetString("EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ふじ.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 文法.
        /// </summary>
        internal static string Grammatiic {
            get {
                return ResourceManager.GetString("Grammatiic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 文法の分類.
        /// </summary>
        internal static string KlassiGRAMMATIC {
            get {
                return ResourceManager.GetString("KlassiGRAMMATIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ソース.
        /// </summary>
        internal static string KODISVOD {
            get {
                return ResourceManager.GetString("KODISVOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 言語を変える.
        /// </summary>
        internal static string Langvich {
            get {
                return ResourceManager.GetString("Langvich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 分析方法.
        /// </summary>
        internal static string MetodAnaliza {
            get {
                return ResourceManager.GetString("MetodAnaliza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 開ける.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на プログラムについて.
        /// </summary>
        internal static string Oprogamme {
            get {
                return ResourceManager.GetString("Oprogamme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на キャンセル.
        /// </summary>
        internal static string Otmena {
            get {
                return ResourceManager.GetString("Otmena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на パーサー.
        /// </summary>
        internal static string Parser {
            get {
                return ResourceManager.GetString("Parser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 繰り返す.
        /// </summary>
        internal static string Povtor {
            get {
                return ResourceManager.GetString("Povtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 編集.
        /// </summary>
        internal static string Pravka {
            get {
                return ResourceManager.GetString("Pravka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на テキスト例.
        /// </summary>
        internal static string PrimerTEXT {
            get {
                return ResourceManager.GetString("PrimerTEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 打ち上げ.
        /// </summary>
        internal static string Pusk {
            get {
                return ResourceManager.GetString("Pusk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на こんにちは.
        /// </summary>
        internal static string RichTextBox_Japanese {
            get {
                return ResourceManager.GetString("RichTextBox_Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 保存.
        /// </summary>
        internal static string Safe {
            get {
                return ResourceManager.GetString("Safe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 名前を付けて保存.
        /// </summary>
        internal static string SafeKak {
            get {
                return ResourceManager.GetString("SafeKak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на フォントを変更する.
        /// </summary>
        internal static string SHRIFT {
            get {
                return ResourceManager.GetString("SHRIFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 文章.
        /// </summary>
        internal static string TXT {
            get {
                return ResourceManager.GetString("TXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 言語を返す.
        /// </summary>
        internal static string Vernutiazik {
            get {
                return ResourceManager.GetString("Vernutiazik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ビュー.
        /// </summary>
        internal static string VID {
            get {
                return ResourceManager.GetString("VID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ハイライト.
        /// </summary>
        internal static string Videlit {
            get {
                return ResourceManager.GetString("Videlit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на カット.
        /// </summary>
        internal static string VIREZAT {
            get {
                return ResourceManager.GetString("VIREZAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 助けを呼びます.
        /// </summary>
        internal static string VizovCPravki {
            get {
                return ResourceManager.GetString("VizovCPravki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на タスク.
        /// </summary>
        internal static string Zadacha {
            get {
                return ResourceManager.GetString("Zadacha", resourceCulture);
            }
        }
    }
}
